# Generated by Django 5.0.7 on 2026-05-26 02:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='upload', max_length=20)),
                ('original_image', models.ImageField(upload_to=api.models.upload_path)),
                ('detected_image', models.ImageField(blank=True, null=True, upload_to=api.models.result_path)),
                ('label', models.CharField(default='watermelon', max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('bbox', models.JSONField(default=dict)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
