# Generated by Django 5.0.7 on 2026-05-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrecord',
            name='predicted_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='ripeness',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='sweetness',
            field=models.FloatField(default=0.0),
        ),
    ]
