# Generated by Django 5.0.7 on 2026-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedPost',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
